name: Test & Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn
        name: Install dependencies
      - run: yarn test
        name: Run tests
      #- uses: romeovs/lcov-reporter-action@v0.2.11
      #  name: Post code coverage report
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    lcov-file: ./coverage/lcov.info
